### ISSUE TITLE
Should filters stack / are they chainable?

### ISSUE THREAD

**Issue by turnerniles** [pat310/quick-pivot#52]
Should filters stack / are they chainable?  Or do we only allow one filter at a time?

`const dataArray = [
 ['name', 'gender', 'house', 'age'],
 ['Jon', 'm', 'Stark', 14],
 ['Arya', 'f', 'Stark', 10],
 ['Cersei', 'f', 'Baratheon', 38],
 ['Tywin', 'm', 'Lannister', 67],
 ['Tyrion', 'm', 'Lannister', 34],
 ['Joffrey', 'm', 'Baratheon', 18],
 ['Bran', 'm', 'Stark', 8],
 ['Jaime', 'm', 'Lannister', 32],
 ['Sansa', 'f', 'Stark', 12]
];`

`const testPivot = new pivot(dataArray, ['age'], ['house','gender'], [], 'sum');`
`testPivot.filter("house", ["Stark"], 'exclude')`
`testPivot.filter("gender", ["m"], 'exclude')`

returns

`
"[{"value":["sum ","Stark","Baratheon"],"depth":0,"type":"colHeader","row":0},{"value":["sum ","f","f"],"depth":1,"type":"colHeader","row":1},{"value":["10",null,""],"type":"data","depth":0,"row":2},{"value":["12",null,""],"type":"data","depth":0,"row":3},{"value":["38","",null],"type":"data","depth":0,"row":4}]"
`

Which is the result of the second filter (first filter is not applied).

**Comment by pat310** [comment]
Closed in #54

**Comment by turnerniles** [comment]
Reopened wrong issue.
