### ISSUE TITLE
Totals functionality

### ISSUE THREAD

**Issue by turnerniles** [pat310/quick-pivot#53]
QuickPivot should return row and column totals and have the option to turn them on/off. Should this be done in the quickpivot logic or can it be done in a custom aggregator?

**Comment by pat310** [comment]
@turnerniles We'll do this in the quick-pivot. We could add another row to the "table" that is returned, the row would be of `type: 'sum'`.

Should this just be a count or summation, or should it use whatever the user puts in?
Do we also want to add a column for aggregation over the columns like the request [https://github.com/turnerniles/react-virtualized-pivot/issues/100](https://github.com/turnerniles/react-virtualized-pivot/issues/100)?

**Comment by turnerniles** [comment]
@pat310 We probably need to add both row and column total support but could start with row totals. As you mentioned I agree the aggregator selected or provided should be run over all the results in the row/column sum/count/min/max so the sum/count/min/max of that row/column is returned. I don't think we need an additional custom function at least for now.
