### ISSUE TITLE
Row and column total header 

### ISSUE THREAD

**Issue by turnerniles** [pat310/quick-pivot#69]
Should row and column totals both have blank headers, or text headers of 'Totals' similar to PivotTable.js? Currently row total header is blank and column total header has text of 'aggregated'. See screenshot below.

<img width="546" alt="screen shot 2017-12-03 at 9 45 47 pm" src="https://user-images.githubusercontent.com/8146241/33534161-bda73918-d873-11e7-8fe0-960dbcb2cf44.png">

**Comment by pat310** [comment]
Closed in #72
