### ISSUE TITLE
Preserving order or column and row entries?

### ISSUE THREAD

**Issue by corvana-nbaker** [pat310/quick-pivot#70]
Is there a way of setting the sorting algorithm in play? My initial data is sorted properly, but upon pivot seems to be randomized (though consistent).

**Comment by pat310** [comment]
Right now the data gets sorted [before pivoting](https://github.com/pat310/quick-pivot/blob/master/src/logic.js#L33) just using the native javascript array sort method. I could set it up so this doesn't happen automatically or so that it could optionally take some sort callback...

**Comment by corvana-nbaker** [comment]
A delegate function would be great! I'll link the source over and test it with a no-op.

**Comment by pat310** [comment]
Closed in #71
